### ISSUE TITLE
hhvm in allowed failures

### ISSUE THREAD

**Issue by fntlnz** [gianarb/console-skeleton-app#14]
zend-console fails on hhvm because of 
```
Call to undefined function ZF\Console\cli_set_process_title() 
```

Since they have hhvm and php 7 in allowed failures I think that this project should do the same thing in order to avoid false build failures.

**Comment by samsonasik** [comment]
I've created PR #15 for it.

**Comment by gianarb** [comment]
Thanks @fntlnz for this issue and @samsonasik for your fix! :+1:
