### ISSUE TITLE
Dependence Injection

### ISSUE THREAD

**Issue by gianarb** [gianarb/console-skeleton-app#5]
I'm thinking a necessary integrations with DiC

**Which?** Symfony\Dic, ServiceLocator, PHP-DI..

**Comment by samsonasik** [comment]
that's cool, should can choose what the container as options

**Comment by gianarb** [comment]
in first this feature requires new dispatcher because the idea is 

You could define that `command_hello` require `doctrine` and `monolog`

Dispatcher loads and configures the command from DI
```
$di->get("command_hello");
```

To choose your container is necessary an Interface and I don't know if it is a good requirement

**Comment by gianarb** [comment]
PHP-DI + Service Locator
@samsonasik what do you think? :)

**Comment by samsonasik** [comment]
I didn't try php-di, how about zend-servicemanager?

**Comment by gianarb** [comment]
Sorry Service Locator for me is == service manager :D..

ServiceManager cover a lot of requests but a real DI is very comfortable :P

**Comment by samsonasik** [comment]
ok +1 then ;)

Warm Regards,

Abdul Malik Ikhsan


2015-07-06 19:30 GMT+07:00 Gianluca Arbezzano <notifications@github.com>:

**Comment by samsonasik** [comment]
I propose the config can be something like:

```php
return [
    'app' => "this is my app",
    'container_config' => [
           'type' => 'zf_service_manager', // can be phpdi or other ?
           'setup' => [
                    'service_manager' => [
                           'invokables' => [] // ...
                    ],
            ],
    ],
];
```
and to implement this, we need to make custom console adapter to fetch the service container ?

**Comment by gianarb** [comment]
Yes I'm working to understand what is the best implementation maybe we can try to extends a lot of ZF\Console classes.. :)

**Comment by samsonasik** [comment]
cool :+1:

**Comment by gianarb** [comment]
Zf\Console is not reusable -.- :-1: :hankey:
I'm thinking to use [penny](gianarb/penny) to build this application

**Comment by samsonasik** [comment]
awesome, that's seems usable for this case

**Comment by gianarb** [comment]
I don't know but ZF\Console has not Interface or other tricks to extends itself.. Now I push a PR with ZF\Console.. Without penny! :)
